import { GearSlotData } from "./types";

export const gearSlotData: GearSlotData[] = [
  { slotName: "Head", imageName: "Head.jpg", gearJsSlotName: "head" },
  { slotName: "Hands", imageName: "Hands.jpg", gearJsSlotName: "hands" },
  { slotName: "Neck", imageName: "Neck.jpg", gearJsSlotName: "neck" },
  { slotName: "Waist", imageName: "Waist.jpg", gearJsSlotName: "waist" },
  {
    slotName: "Shoulders",
    imageName: "Shoulders.jpg",
    gearJsSlotName: "shoulder",
  },
  { slotName: "Legs", imageName: "Legs.jpg", gearJsSlotName: "legs" },
  { slotName: "Back", imageName: "Back.jpg", gearJsSlotName: "back" },
  { slotName: "Feet", imageName: "Feet.jpg", gearJsSlotName: "feet" },
  { slotName: "Chest", imageName: "Chest.jpg", gearJsSlotName: "chest" },
  { slotName: "Finger 1", imageName: "Finger.jpg", gearJsSlotName: "finger1" },
  { slotName: "Shirt", imageName: "Shirt.jpg", gearJsSlotName: null },
  { slotName: "Finger 2", imageName: "Finger.jpg", gearJsSlotName: "finger2" },
  { slotName: "Tabard", imageName: "Tabard.jpg", gearJsSlotName: null },
  {
    slotName: "Trinket 1",
    imageName: "Trinket.jpg",
    gearJsSlotName: "trinket1",
  },
  { slotName: "Wrists", imageName: "Wrists.jpg", gearJsSlotName: "wrist" },
  {
    slotName: "Trinket 2",
    imageName: "Trinket.jpg",
    gearJsSlotName: "trinket2",
  },
  {
    slotName: "Main Hand",
    imageName: "MainHand.jpg",
    gearJsSlotName: "mainhand",
  },
  { slotName: "Ranged", imageName: "Ranged.jpg", gearJsSlotName: "ranged" },
  { slotName: "Off Hand", imageName: "OffHand.jpg", gearJsSlotName: "offhand" },
];

export const classNames = ["Warrior", "Rogue", "Mage", "Priest"];

export const equipmentStats = [
  "Attack Power",
  "Strength",
  "Agility",
  "Hit",
  "Skill",
  "Miss",
  "Crit",
  "Crit Cap",
  "Dmg %",
  "Haste",
  "Sets",
] as const;

export const raceData = [
  {
    name: "Human",
    str: 120,
    agi: 80,
    sta: 110,
    int: 30,
    skill_0: 5,
    skill_1: 5,
    skill_2: 0,
    skill_3: 0,
  },
  {
    name: "Dwarf",
    str: 122,
    agi: 76,
    sta: 113,
    int: 29,
    skill_0: 0,
    skill_1: 0,
    skill_2: 0,
    skill_3: 0,
  },
  {
    name: "Gnome",
    str: 115,
    agi: 83,
    sta: 109,
    int: 35,
    skill_0: 0,
    skill_1: 0,
    skill_2: 0,
    skill_3: 0,
  },
  {
    name: "Night Elf",
    str: 117,
    agi: 85,
    sta: 109,
    int: 30,
    skill_0: 0,
    skill_1: 0,
    skill_2: 0,
    skill_3: 0,
  },
  {
    name: "Orc",
    str: 123,
    agi: 77,
    sta: 112,
    int: 27,
    skill_0: 0,
    skill_1: 0,
    skill_2: 0,
    skill_3: 5,
  },
  {
    name: "Tauren",
    str: 125,
    agi: 75,
    sta: 112,
    int: 25,
    skill_0: 0,
    skill_1: 0,
    skill_2: 0,
    skill_3: 0,
  },
  {
    name: "Troll",
    str: 121,
    agi: 82,
    sta: 111,
    int: 26,
    skill_0: 0,
    skill_1: 0,
    skill_2: 0,
    skill_3: 0,
  },
  {
    name: "Undead",
    str: 119,
    agi: 78,
    sta: 111,
    int: 28,
    skill_0: 0,
    skill_1: 0,
    skill_2: 0,
    skill_3: 0,
  },
];

export const imageDomain = "https://wow.zamimg.com/images/wow/icons/medium/";
